import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { upload } from "@vercel/blob/client";
import "./styles.css";

const labels = { pdf: "PDF", pptx: "PPTX", docx: "DOCX", xlsx: "XLSX", md: "MD", png: "PNG", jpg: "JPG" };
function Badge({ children, blue }) { return <span className={blue ? "badge blue" : "badge"}>{children}</span>; }
function Header({ page, setPage }) {
  return <header className="topbar"><b>CATL 投资部 AI 化展示站</b><nav>{[["home","流程总览"],["skills","Skill 库"],["cases","项目案例"],["library","资料库"],["upload","上传"]].map(([id,label])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}>{label}</button>)}</nav></header>;
}
function Home({ data }) {
  const [step, setStep] = useState(null);
  const active = step || data.sop[0];
  return <main className="page"><section className="intro"><div><p className="eyebrow">AI Investment Memo Workflow</p><h1>从项目资料池到立项报告 Slides 的可复用 AI 协作流程</h1><p>用结构化 SOP 连接资料收集、行研补充、投资逻辑、三 md、Slide 图片、贴图 PPT 和可编辑 PPT。</p></div><div className="metrics"><span><b>{data.sop.length}</b>SOP</span><span><b>{data.skills.length}</b>Skill</span><span><b>{data.cases.length}</b>案例</span><span><b>{data.artifacts.length}</b>文件</span></div></section><section className="flow">{data.sop.map(s=><button className={active?.id===s.id?"node active":"node"} key={s.id} onClick={()=>setStep(s)}><Badge blue>步骤 {s.order}</Badge><strong>{s.shortTitle}</strong><small>{s.title}</small></button>)}</section>{active&&<section className="panel"><h2>{active.title}</h2><p>{active.description}</p><div className="cols"><Info title="输入" items={active.inputs}/><Info title="输出" items={active.outputs}/><Info title="检查点" items={active.humanReviewPoints}/></div></section>}</main>;
}
function Info({ title, items=[] }) { return <div className="info"><h3>{title}</h3><ul>{items.map(i=><li key={i}>{i}</li>)}</ul></div>; }
function Skills({ skills }) { const [id,setId]=useState(skills[0]?.id); const s=skills.find(x=>x.id===id)||skills[0]; return <main className="page"><h1>AI Skill 库</h1><div className="tabs">{skills.map(x=><button className={x.id===id?"active":""} onClick={()=>setId(x.id)} key={x.id}>{x.name}</button>)}</div>{s&&<section className="panel"><Badge blue>{s.stage}</Badge><h2>{s.name}</h2><p>{s.definition}</p><div className="cols"><Info title="输入" items={s.inputs}/><Info title="输出" items={s.outputs}/><Info title="质量门槛" items={s.qualityGates}/></div></section>}</main>; }
function Cases({ cases, artifacts }) { const [id,setId]=useState(cases[0]?.id); const p=cases.find(x=>x.id===id)||cases[0]; return <main className="page"><div className="tabs">{cases.map(x=><button className={x.id===id?"active":""} onClick={()=>setId(x.id)} key={x.id}>{x.name}</button>)}</div><section className="case"><aside>{p?.caseSteps?.map(s=><a key={s.id}>{s.title}</a>)}</aside><article className="panel"><h1>{p?.name}</h1><p>{p?.summary}</p><Badge>{p?.industry}</Badge>{p?.caseSteps?.map(s=><div className="step" key={s.id}><h2>{s.title}</h2><p>{s.description}</p>{s.skillUsed?.map(k=><Badge blue key={k}>{k}</Badge>)}</div>)}</article></section><Gallery artifacts={artifacts.filter(a=>a.projectId===p?.id).slice(0,8)}/></main>; }
function Gallery({ artifacts }) { return <section className="grid">{artifacts.map(a=><a className="card" href={a.url} target="_blank" key={a.id}><div className="file">{labels[a.fileType]||a.fileType}</div><b>{a.title}</b><small>{a.projectName||a.projectId} · {a.version||"未标版本"}</small></a>)}</section>; }
function Library({ data }) { const [f,setF]=useState({projectId:"all",fileType:"all"}); const rows=useMemo(()=>data.artifacts.filter(a=>(f.projectId==="all"||a.projectId===f.projectId)&&(f.fileType==="all"||a.fileType===f.fileType)),[data.artifacts,f]); const types=[...new Set(data.artifacts.map(a=>a.fileType).filter(Boolean))]; return <main className="page"><h1>公开资料库</h1><div className="filters"><select onChange={e=>setF({...f,projectId:e.target.value})}><option value="all">全部项目</option>{data.cases.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select onChange={e=>setF({...f,fileType:e.target.value})}><option value="all">全部类型</option>{types.map(t=><option key={t}>{t}</option>)}</select></div><table><thead><tr><th>文件名</th><th>项目</th><th>类型</th><th>版本</th><th>操作</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.fileName}</td><td>{a.projectName||a.projectId}</td><td><Badge>{labels[a.fileType]||a.fileType}</Badge></td><td>{a.version||"-"}</td><td><a href={a.url} target="_blank">打开</a></td></tr>)}</tbody></table></main>; }
function UploadPage() { const [status,setStatus]=useState(""); async function submit(e){e.preventDefault(); const form=new FormData(e.currentTarget); const files=[...form.getAll("files")].filter(x=>x?.name); try{ for(const file of files){ await upload(file.name,file,{access:"public",handleUploadUrl:"/api/upload-token"}); } setStatus(`已上传到 Vercel Blob：${files.length} 个文件`);}catch{setStatus("请先在 Vercel 配置 BLOB_READ_WRITE_TOKEN。")}} return <main className="page"><h1>公开上传</h1><form className="panel form" onSubmit={submit}><input name="files" type="file" multiple/><input name="projectId" placeholder="projectId"/><input name="sopStepId" placeholder="sopStepId"/><input name="title" placeholder="标题"/><button>上传到 Vercel Blob</button></form><p>{status}</p></main>; }
function App(){ const [page,setPage]=useState("home"); const [data,setData]=useState({sop:[],skills:[],cases:[],artifacts:[]}); useEffect(()=>{Promise.all([fetch("/data/frontend_data_contract.json").then(r=>r.json()),fetch("/data/asset_manifest.json").then(r=>r.json())]).then(([c,m])=>setData({sop:c.sampleData.sopSteps,skills:c.sampleData.skills,cases:c.sampleData.caseProjects,artifacts:m.artifacts}))},[]); return <><Header page={page} setPage={setPage}/>{page==="home"&&<Home data={data}/>} {page==="skills"&&<Skills skills={data.skills}/>} {page==="cases"&&<Cases cases={data.cases} artifacts={data.artifacts}/>} {page==="library"&&<Library data={data}/>} {page==="upload"&&<UploadPage/>}</>; }
createRoot(document.getElementById("root")).render(<App/>);
